name: Test

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
      
            steps:
            - uses: actions/checkout@v1
            - name: Run tests
              run: |
                  make ct
                  make cover
            - uses: actions/upload-artifact@v1
              with:
                  path: _build/emqx+test/logs
        
        services:
            mongo:
                image: mongo:4.1
                env:
                    MONGO_INITDB_DATABASE: mqtt
                command: --bind_ip_all
                